### ISSUE TITLE
No Shiny application exists at the path "metaOmics"

### ISSUE THREAD

**Issue by Ocreatus** [metaOmics/metaOmics#63]
Hi,
I am new to R (using now 4.0.3-Windows 64bit), and following the installing instructions in metaOmics tutorial. 
I dowloaded these: 
install.packages(c('GSA', 'combinat', 'samr', 'survival', 'cluster', 'gplots', 'ggplot2', 'irr', 'shape', 'snow',
'snowfall', 'igraph','PMA'))
The biocLite function was not working so I installed Bioconductor packages using BiocManager manually.
Then I downloaded doMC, this worked well: install.packages('doMC', repos='http://R-Forge.R-project.org') 
Then I set a new working directory.
This command not worked:
> git clone https://github.com/metaOmic/metaOmics
Error: unexpected symbol in "git clone"
 I downloaded metaOmics-master file (ZIP) from github (Clone-HTTPS-Download ZIP) and extracted files to my working directory.
I installed shiny. 
Then I got this error:
> shiny::runApp('metaOmics', port=9987, launch.browser=T)
Error in shinyAppDir(x) : 
  No Shiny application exists at the path "metaOmics"
I tried earlier versions of R: R3.3 and R3.4. and faced the same problem. 
I don't know what I did wrong. Could you please help me? 
I really want to use metaOmics in my transcriptome meta-analysis study.
Thank you

**Comment by Caleb-Huo** [comment]
Hi there:

Can you check your current working directory in R?
```
getwd()
```
And make sure the metaOmics folder downloaded from GitHub is at your current working directory?

Alternatively in R, can you try
```
dir()
```

This will show all files/folders under your current working directory.

**Comment by Ocreatus** [comment]
Hi,

I am still trying to solve this problem. Thank you so much for your reply.

I uninstalled all r versions  from my computer and the packages I installed earlier. I installed R again.

I am using Rx64 4.0.3 right now.


I installed shiny first this time,  not  GSA', 'combinat', 'samr', 'survival', 'cluster', 'gplots', 'ggplot2', 'irr', 'shape', 'snow', 'snowfall', 'igraph', 'doMC', 'PMA' etc :

downloaded binary packages are in
        C:\Users\Sevcan ATAY\AppData\Local\Temp\Rtmpw7KtsD\downloaded_packages

Shiny is working on its own:

> library (shiny)
> runExample("01_hello")

Listening on http://127.0.0.1:6958


getwd()
[1] "C:/Users/Sevcan ATAY/Documents/WORKINGDIRECTORY"
>  shiny::runApp('metaOmics', port=9987, launch.browser=T)
Error in shinyAppDir(x) :
  No Shiny application exists at the path "metaOmics"


And the meta-omics folder is in my working directory:

[cid:image003.png@01D6B2E5.7B835DB0]


How can I solve this problem?
Thank you in advance for your help,

Sevcan


Kimden: Zhiguang Huo (Caleb)<mailto:notifications@github.com>
Gönderilme: 4 Kasım 2020 Çarşamba 19:39
Kime: metaOmics/metaOmics<mailto:metaOmics@noreply.github.com>
Bilgi: Ocreatus<mailto:sevcan.atay@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [metaOmics/metaOmics] No Shiny application exists at the path "metaOmics" (#63)


Hi there:

Can you check your current working directory in R?

getwd()

And make sure the metaOmics folder downloaded from GitHub is at your current working directory?

Alternatively in R, can you try

dir()

This will show all files/folders under your current working directory.

**Comment by Ocreatus** [comment]
Hi,

I changed the name of the file (not metaOmics but metaOmics-master), and got another error:

> dir()
[1] "metaOmics-master"
> shiny::runApp('metaOmics-master', port=9987, launch.browser=T)
Error in library(preproc) : there is no package called ‘preproc’

Sevcan

Kimden: Zhiguang Huo (Caleb)<mailto:notifications@github.com>
Gönderilme: 4 Kasım 2020 Çarşamba 19:39
Kime: metaOmics/metaOmics<mailto:metaOmics@noreply.github.com>
Bilgi: Ocreatus<mailto:sevcan.atay@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [metaOmics/metaOmics] No Shiny application exists at the path "metaOmics" (#63)


Hi there:

Can you check your current working directory in R?

getwd()

And make sure the metaOmics folder downloaded from GitHub is at your current working directory?

Alternatively in R, can you try

dir()

This will show all files/folders under your current working directory.

**Comment by Caleb-Huo** [comment]
Hi Sevcan:

I should have fixed this problem.
The problem was that R kept updating itself, and some of our function to install packages were no longer compatible.
Let me know if this could solve the problem.

Thanks

Caleb

**Comment by sahalthahir** [comment]
Hi there,

I had a similar issue and once I confirmed the working directory and tried 
runApp() 
in the console without any arguments it worked.

Hope this helps,
Sahal
